"""empty message

Revision ID: cb2eddb6af97
Revises: None
Create Date: 2019-03-24 11:00:01.573967

"""

# revision identifiers, used by Alembic.
revision = 'cb2eddb6af97'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FanInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FanInfo')
    # ### end Alembic commands ###
